version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: 'always'
    ports: 
      - '3001:3000'
  backend:
    build: ./backend
    depends_on:
      - db
    restart: 'always'
    ports:
      - '3000:3000'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # TODO Add super secret vars below in an env file
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    volumes:
      - "./db/structure.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/2.sql"

